version: '3.5'

services:

  redis-server:
    image: redis
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 6379:6379
    networks:
      - backend-net

  redis-mgmt:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis-server
      - REDIS_DB=1
    ports:
      - 8081:8081
    restart: always
    networks:
      - backend-net

networks:
  backend-net: